Update branchesTest.yml
added jira ticket check

diff --git a/.github/workflows/branchesTest.yml b/.github/workflows/branchesTest.yml
--- a/.github/workflows/branchesTest.yml
+++ b/.github/workflows/branchesTest.yml
@@ -1,8 +1,5 @@
 name: Branch naming
 
-#on:
- # create:
-
 on:
   push:
     branches-ignore:
@@ -13,12 +10,6 @@ on:
       - main
       - develop
 
-#on:
-#  push:
-#    branches-ignore:
- #     - main
-  #    - develop
- # pull_request:
 
 jobs:
   branch-naming-rules:
@@ -65,6 +56,32 @@ jobs:
           regex: '^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-[0-9]{5}$'
           min_length: 10
           max_length: 100
+
+      - name: Extract Jira Ticket Key
+        id: extract
+        run: |
+          env:
+          BRANCH_NAME: ${{ github.ref_name }}
+          echo "Branch: $BRANCH_NAME"
+          TICKET=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]{2,}-[0-9]{5}')
+          echo "Extracted ticket: $TICKET"
+          echo "ticket=$TICKET" >> $GITHUB_OUTPUT
+
+      - name: Validate Jira Ticket Exists
+        run: |
+             echo "Checking Jira ticket: ${{ steps.extract.outputs.ticket }}"
+             RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
+               -u "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
+               -X GET \
+               -H "Accept: application/json" \
+               "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.ticket }}")
+   
+             if [ "$RESPONSE" -ne 200 ]; then
+               echo "❌ Jira ticket not found: ${{ steps.extract.outputs.ticket }}"
+               exit 1
+             else
+               echo "✅ Jira ticket exists: ${{ steps.extract.outputs.ticket }}"
+   
 
       - name: Comment on PR if branch name is invalid
         if: failure() && github.event_name == 'pull_request'
